### ISSUE TITLE
Batch Script compatability

### ISSUE THREAD

**Issue by MrLEADshed** [EricTetz/keyrate#3]
I am not sure if the settings are maintained after a reboot,
so I wanted to write a batch script to be launched on every start up.
![Screenshot 2022-01-08 160306](https://user-images.githubusercontent.com/53165608/148635195-a642be24-ce56-458c-89b7-db9a2755f61e.png)
The test run of this file resulted in an endless array of keyrate commands written in cmd window without any effect on actual keyrate
![Screenshot 2022-01-08 160604](https://user-images.githubusercontent.com/53165608/148635247-14ef168a-109b-4137-a31e-0411c9790c3a.png)
(it kept on going on forever like that)
is there any workaround or a detail that im missing

**Comment by minig0d** [comment]
> is there any workaround or a detail that im missing

Change your batch file to say keyrate.exe rather than keyrate.  Since your .bat is named the same as the exe, its just calling itself repeatedly.  Get in the habit of always using the file extension (and ideally the full path) so you know what program you're running and to prevent security issues.  You can confirm the aforementioned is happening by opening a command prompt there and typing "which keyrate" and it should say c:\your\path\to\keyrate.**BAT**

But also, this should be called with 2 arguments.  This repo doesn't have documentation, but if you look at the code:
`puts ("Usage: keyrate <delay ms> <repeat ms>\nCall with no parameters to disable.");`
I.e. you should be running it like "keyrate 200 30".  

Without the numbers you're just disabling it repeatedly.

But even having a batch file to run this is a waste (unless you need it for something else).   Either:

1) run it from a scheduled task that triggers at startup or login. You just need to create a scheduled task and in the Program/script box put: "c:\your\path\to\keyrate.exe"   and in "Add arguments optional" put "250 10", or whatever your preference is.  (PS. At login may be overboard, but honestly it's so tiny it may add 1ms to the login so oh well.)

2) Create a windows shortcut and and put the shortcut in your start menu's startup folder instead of a batch file.

**Comment by MrLEADshed** [comment]
thanks a bunch!
I could never find a good guide on it honestly, plus I got an easy explanation for task scheduler
I couldn't be happier
